"use client";

import { useCallback, useEffect, useRef, useState } from "react";

import { generateAIReport } from "@/lib/api";
import type {
  AggregateAnalysisResult,
  GrowthAnalysisResult,
} from "@/types/analysis";
import type {
  AIReport,
  ConfidenceLevel,
  ReportEvidence,
} from "@/types/ai-report";

interface AIReportSectionProps {
  analysis: GrowthAnalysisResult | AggregateAnalysisResult;
  autoGenerate?: boolean;
}

const CONFIDENCE_LABELS: Record<ConfidenceLevel, string> = {
  high: "高置信度",
  medium: "中置信度",
  low: "低置信度",
};

const GROWTH_DRIVER_LABELS = {
  traffic: "流量规模扩大",
  conversion: "转化效率改善",
  combined: "流量与转化双重驱动",
  mixed: "多因素方向不一致",
  unavailable: "暂无法判断",
} as const;

export function AIReportSection({
  analysis,
  autoGenerate = false,
}: AIReportSectionProps) {
  const [report, setReport] = useState<AIReport | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const hasAutoGenerated = useRef(false);

  const handleGenerate = useCallback(async () => {
    setIsLoading(true);
    setError(null);

    try {
      const nextReport = await generateAIReport(analysis);
      setReport(nextReport);
    } catch (requestError) {
      setError(
        requestError instanceof Error
          ? requestError.message
          : "AI 诊断生成失败，可重新生成。",
      );
    } finally {
      setIsLoading(false);
    }
  }, [analysis]);

  useEffect(() => {
    if (!autoGenerate || hasAutoGenerated.current) return;
    hasAutoGenerated.current = true;
    void handleGenerate();
  }, [autoGenerate, handleGenerate]);

  return (
    <section className="dashboard-section ai-report-section">
      <div className="section-heading ai-section-heading">
        <div>
          <p className="section-kicker">AI growth diagnosis</p>
          <h2>AI 增长诊断</h2>
        </div>
        <div className="ai-heading-actions">
          <p>
            基于后端已验证的指标、漏斗和经营洞察，生成问题、证据与优先建议。
          </p>
          <button
            className="ai-generate-button"
            disabled={isLoading}
            onClick={() => void handleGenerate()}
            type="button"
          >
            {isLoading
              ? "正在生成诊断…"
              : error && !report
                ? "重新生成"
                : report
                  ? "更新增长诊断"
                  : "生成增长诊断"}
          </button>
        </div>
      </div>

      {error ? (
        <div className="feedback feedback-error ai-feedback">
          <strong>AI 诊断生成失败，可重新生成。</strong>
          <span>{error}</span>
        </div>
      ) : null}

      {!report ? (
        <AIReportPlaceholder isLoading={isLoading} />
      ) : (
        <AIReportContent report={report} />
      )}
    </section>
  );
}

function AIReportPlaceholder({ isLoading }: { isLoading: boolean }) {
  return (
    <div
      aria-busy={isLoading}
      className={`ai-report-placeholder${isLoading ? " is-loading" : ""}`}
    >
      <div className="ai-placeholder-mark">AI</div>
      <div>
        <h3>
          {isLoading ? "正在研判经营信号" : "获取面向决策的增长诊断"}
        </h3>
        <p>
          {isLoading
            ? "Dashboard 已可正常查看，AI 正在整理重点问题与建议。"
            : "诊断将聚焦核心结论、重点问题、数据证据和优先行动。"}
        </p>
      </div>
      <span>问题 · 证据 · 建议</span>
    </div>
  );
}

function AIReportContent({ report }: { report: AIReport }) {
  return (
    <div className="ai-report-panel">
      <div className="ai-summary">
        <span>核心结论</span>
        <p>{report.core_conclusion}</p>
      </div>

      {report.growth_explanation ? (
        <div className="growth-source-analysis">
          <div>
            <span>增长驱动</span>
            <strong>
              {GROWTH_DRIVER_LABELS[report.growth_explanation.growth_driver]}
            </strong>
            <small>分析对象：{report.growth_explanation.dimension_value}</small>
          </div>
          <div>
            <span>原因</span>
            <p>{report.growth_explanation.why}</p>
          </div>
          <div>
            <span>主要贡献</span>
            <p>{report.growth_explanation.main_contribution}</p>
          </div>
          <EvidenceList evidence={report.growth_explanation.evidence} compact />
        </div>
      ) : null}

      {report.key_issues.length ? (
        <div className="ai-report-block">
          <ReportBlockHeading
            index="01"
            title="重点问题"
            description="每条判断均保留可追溯的数据证据"
          />
          <div className="insight-grid">
            {report.key_issues.map((issue, index) => (
              <article className="insight-card" key={`${issue.issue}-${index}`}>
                <div className="insight-card-header">
                  <span className="finding-badge">
                    问题 {String(index + 1).padStart(2, "0")}
                  </span>
                  <span className={`confidence-badge confidence-${issue.confidence}`}>
                    {CONFIDENCE_LABELS[issue.confidence]}
                  </span>
                </div>
                <h4>{issue.issue}</h4>
                <EvidenceList evidence={issue.evidence} />
                <div className="insight-detail interpretation">
                  <span>影响判断</span>
                  <p>{issue.impact}</p>
                </div>
              </article>
            ))}
          </div>
        </div>
      ) : null}

      <div className="ai-report-columns">
        {report.priority_actions.length ? (
          <div className="ai-report-block">
            <ReportBlockHeading
              index="02"
              title="优先建议"
              description="建议动作与问题证据直接对应"
            />
            <ol className="action-list">
              {report.priority_actions.map((item, index) => (
                <li key={`${item.target_metric}-${index}`}>
                  <span>{String(index + 1).padStart(2, "0")}</span>
                  <div>
                    <p>{item.action}</p>
                    <div className="action-reason">{item.reason}</div>
                    {item.experiment ? (
                      <div className="action-experiment">
                        <strong>建议验证</strong>
                        <span>{item.experiment}</span>
                      </div>
                    ) : null}
                    <div className="action-meta">
                      <strong>{item.applicable_to}</strong>
                      <span>{item.target_metric}</span>
                    </div>
                  </div>
                </li>
              ))}
            </ol>
          </div>
        ) : null}

        {report.opportunities.length ? (
          <div className="ai-report-block">
            <ReportBlockHeading
              index="03"
              title="增长机会"
              description="优先关注可验证的改善与扩量空间"
            />
            <div className="opportunity-list">
              {report.opportunities.map((item, index) => (
                <article className="opportunity-item" key={`${item.target}-${index}`}>
                  <div className="opportunity-channel">
                    <span className="channel-dot" />
                    <strong>{item.target}</strong>
                  </div>
                  <p>{item.recommendation}</p>
                  <EvidenceList evidence={item.evidence} compact />
                </article>
              ))}
            </div>
          </div>
        ) : null}
      </div>

      {report.limitations.length ? (
        <div className="ai-limitations">
          <strong>数据边界</strong>
          <span>{report.limitations.join("；")}</span>
        </div>
      ) : null}
    </div>
  );
}

function EvidenceList({
  compact = false,
  evidence,
}: {
  compact?: boolean;
  evidence: ReportEvidence[];
}) {
  if (compact) {
    return (
      <small>
        {evidence
          .flatMap((item) => item.display_values)
          .join("；")}
      </small>
    );
  }
  return (
    <div className="insight-detail">
      <span>数据证据</span>
      <ul className="ai-evidence-list">
        {evidence.map((item, index) => (
          <li key={`${item.evidence_ref.join("-")}-${index}`}>
            <strong>{item.display_values.join("；")}</strong>
            <span>{item.interpretation}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

function ReportBlockHeading({
  description,
  index,
  title,
}: {
  description: string;
  index: string;
  title: string;
}) {
  return (
    <div className="report-block-heading">
      <span>{index}</span>
      <div>
        <h3>{title}</h3>
        <p>{description}</p>
      </div>
    </div>
  );
}
